name: first_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0
  dotenv: ^4.2.0
  envied: ^0.5.4+1
  equatable: ^2.0.5
  google_generative_ai: ^0.3.2
  http: ^1.2.1
  postgres: ^3.2.0
  riverpod: ^2.5.1
  shelf: ^1.4.1
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  mocktail: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ^5.1.0
